accounts/urls.py
from accounts import views
from django.conf.urls import url

urlpatterns = [
    url(r'^new$', views.new_account, name='new_account'),
    url(r'^(\d+)/$', views.view_account, name='view_account'),
    url(r'^(\d+)/add_transaction$', views.add_transaction, name='add_transaction'),

]

api/urls.py
from rest_framework import routers
from views.py import UserViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

dwallet/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views as accounts_views
from accounts import urls as accounts_urls

from django.conf.urls import url, include




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', accounts_views.home_page, name='home'),
    url(r'^api-auth/', include('rest_framework.urls')),

    url(r'^accounts/', include(accounts_urls)),

]

accounts/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    pass

class Transaction(models.Model):
    text = models.TextField(default='')
    account = models.ForeignKey(Account, default=None, on_delete = models.CASCADE )

api/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from accounts.models import Transaction, Account
# Create your views here.

def home_page(request):
    return render(request, 'home.html')

def view_account(request, account_id):
    account_ = Account.objects.get(id = account_id)
    return render(request, 'account.html', {'account': account_})

def new_account(request):

    account_ = Account.objects.create()

    Transaction.objects.create(text = request.POST['transaction_text'], account = account_)
    return redirect('/accounts/' + str(account_.id) + '/')

def add_transaction(request, account_id):

    account_ = Account.objects.get(id = account_id)
    Transaction.objects.create(text = request.POST['transaction_text'], account = account_)
    return redirect('/accounts/' + str(account_.id) + '/')

api/views.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from django.shortcuts import render

from rest_framework import serializers, viewsets


# Create your views here.
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

accounts/templates/account.html
{% extends 'base.html' %}

{% block header_text %}Your Account{% endblock %}

{% block form_action %}/accounts/{{ account.id }}/add_transaction{% endblock %}

{% block table %}
	<table class="table" id="account_table">
		
	{% for a in account.transaction_set.all %}
		<tr>
			<td>{{forloop.counter}}: {{a.text}}</td>
		</tr>
	{% endfor %}
	</table>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Accounts</title>
	<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<link href="/static/base.css" rel="stylesheet">
</head>
<body>
	 <div class="container">
		 <div class="row">
		 	<div class="col-md-6 col-md-offset-3 jumbotron">
		 		<div class="text-center">
					<h1>{% block header_text %}{% endblock %} </h1>
					<form  method="POST" action="{% block form_action %}{% endblock %}">
						<input class="form-control input-lg" name="transaction_text" id="id_new_account" type="" placeholder="Enter an Account name" >
						{% csrf_token %}
					</form>
		 		</div>
		 	</div>
		 </div>
		 <div class="row">
		 	<div class="col-md-6 col-md-offset-3">
				{% block table %}
				{% endblock %}
		 	</div>
		 </div>
	</div>
</body>
</html>

accounts/templates/home.html
{% extends 'base.html' %}

{% block header_text %} Start a new Account {% endblock %} 

{% block form_action %}/accounts/new{% endblock %} 